# Generated by Django 3.0.7 on 2020-06-09 20:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score1', models.IntegerField(blank=True, null=True)),
                ('score2', models.IntegerField(blank=True, null=True)),
                ('turn', models.IntegerField(blank=True, null=True)),
                ('serving', models.IntegerField()),
                ('finished', models.IntegerField()),
                ('fecha', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'juego',
                'managed': False,
            },
        ),
    ]
