# Generated by Django 3.0.7 on 2020-06-10 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score1', models.IntegerField(blank=True, default=0, null=True)),
                ('score2', models.IntegerField(blank=True, default=0, null=True)),
                ('turn', models.IntegerField(blank=True, default=1, null=True)),
                ('serving', models.IntegerField()),
                ('finished', models.IntegerField(default=0)),
                ('fecha', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('winner', models.IntegerField(default=0)),
                ('player1', models.ForeignKey(db_column='player1', on_delete=django.db.models.deletion.DO_NOTHING, related_name='player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(db_column='player2', on_delete=django.db.models.deletion.DO_NOTHING, related_name='player2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Juego',
                'db_table': 'Juego',
                'managed': True,
            },
        ),
    ]
