# Generated by Django 3.0.7 on 2020-06-09 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Juegos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='juego',
            options={'managed': False, 'verbose_name': 'Juego'},
        ),
    ]
